### ISSUE TITLE
No application icon

### ISSUE THREAD

**Issue by brs17** [pop-os/repoman#13]
When launching repoman from the Pop!_Shop, the application icon (in the alt-tab screen) looks very simplistic(perhaps it just doesn't have an icon since we aren't planning on having repoman launchable from outside of Pop!_Shop). I am under the impression however that it is possible to have an application icon even if there is no desktop icon.

**Comment by isantop** [comment]
This is because there is no .desktop file. We would need to add a .desktop file that doesn't show in GNOME.

**Comment by isantop** [comment]
I believe this is currently fixed.
