### ISSUE TITLE
20.04: Some things have moved from "Updates" to "Extra Sources"

### ISSUE THREAD

**Issue by leviport** [pop-os/repoman#51]
This was a 19.10 install that was upgraded with `pop-upgrade release upgrade systemd -f`. After the upgrade, I noticed that security updates, recommended updates, and unsupported updates were all shown in the "Extra Sources" list instead of on the "Updates" page. All three on the Updates page were unchecked.
![Screenshot from 2020-02-06 10-31-22](https://user-images.githubusercontent.com/13512097/73962877-77e13e80-48cc-11ea-9ab3-0995056fc025.png)
![Screenshot from 2020-02-06 10-31-37](https://user-images.githubusercontent.com/13512097/73962882-79ab0200-48cc-11ea-8641-025167a325b8.png)

**Comment by isantop** [comment]
I can't seem to replicate this issue here, but I noticed there was a recent update to `python3-apt`, which is used by parts of Repoman and its dependencies. Perhaps ensure that those package is updated to version 1.9.5

**Comment by isantop** [comment]
@leviport Can you confirm whether or not this issue is still present on a fully-updated 20.04?

**Comment by leviport** [comment]
Confirmed, still seeing it on clean 19.10 installs that are upgraded to 20.04 with pop-upgrade.

**Comment by isantop** [comment]
@jackpot51 This is also happening with `software-properties-gtk`, which leads me to believe this is being related to the LSB changes (or the Apt changes we made to allow that) and not something that's specific to Repoman

**Comment by jackpot51** [comment]
I think you are right, I will look into it

**Comment by ghisvail** [comment]
I confirm this is still happening. Here are the steps to reproduce:

1. Edit your `/etc/apt/sources.list` and leave only the main Ubuntu repository
2. Open Repoman through Pop!_Shop
3. Go to the **Updates** section and tick the `focal-updates`, `focal-security` and `focal-backports` entries.
4. Close Repoman. You may verify that `/etc/apt/sources.list` now contains the appropriate lines.
5. Open Repoman again : the entries in the **Updates** section are still unticked, whilst new entries corresponding to these repositories have appeared in the **Extra Sources** section.

**Comment by isantop** [comment]
@jackpot51 Did you find out anything from the LSB-related changes we made?

**Comment by jackpot51** [comment]
This should have been fixed by https://github.com/pop-os/default-settings/commit/793f483743cda6a6f4308be4b693952d67a659c4

Can @ghisvail confirm that /usr/share/python-apt/templates/Pop.info and /usr/share/python-apt/templates/Pop.mirrors exist?

**Comment by ghisvail** [comment]
I can confirm both files exist on my system:

```
$ ls -l /usr/share/python-apt/templates/Pop.{info,mirrors}
/usr/share/python-apt/templates/Pop.info -> Ubuntu.info
/usr/share/python-apt/templates/Pop.mirrors -> Ubuntu.info
```
