### ISSUE TITLE
Unchecking all official sources causes updates sources to de-sync from the actual state

### ISSUE THREAD

**Issue by leviport** [pop-os/repoman#70]
If I uncheck all 4 checkboxes in the Settings tab under "Official Sources", the following lines get removed from `/etc/apt/sources.list`:
```
deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
```

When I re-check those four checkboxes, these lines do not get re-added. They should either be commented out instead of removed, or they should be re-added once a box is re-checked. 

EDIT: the same behavior appears in software-properties-gtk

**Comment by isantop** [comment]
After unchecking the four official sources, all of the *.ubuntu.com lines are removed, which is expected. If I re-check one of them, the standard archive.ubuntu.com line is added to the bottom of the file (the other lines are not added) and I can check the other four to enable those components. 

There is an issue that after re-enabling these, the checkboxes in the Updates tab remain checked, but their child repos are not added. Closing and re-opening the app displays the correct state; additionally, the checkboxes can be disabled and re-enabled which correctly syncs the state between the GUI and `sources.list`

Can you confirm that behavior?

**Comment by isantop** [comment]
Okay, so as an update, it looks like what's happening is that unchecking the official sources causes the child repos to become removed (which makes sense if there are no components enabled), but the boxes remain checked in the GUI. So we need to reload the update-tab checks when we make changes to the official sources.
