### ISSUE TITLE
[Repoman] No option for select regional mirror servers and unable to disable 'include source code'

### ISSUE THREAD

**Issue by ghost** [pop-os/repoman#72]
![Screenshot from 2020-09-07 05-58-05](https://user-images.githubusercontent.com/63988538/92336921-e17a3300-f0cf-11ea-8328-d8ca6d2a69dc.png)

'include source code' auto reenable on next launch.

PopOS

![YGtwc](https://user-images.githubusercontent.com/63988538/92336848-2d78a800-f0cf-11ea-8d7e-3076118d37a2.png)
Ubuntu

PopOS 20.04

**Comment by isantop** [comment]
The lack of mirror selection is a known issue, and will be fixed in a future version. 

I will need to investigate the source code issue however, as that should definitely be working.

**Comment by isantop** [comment]
I'm having issues replicating the issues on my end; the Source Code toggle correctly enables and disables the source code repositories, and the box is accurate to state when the window is opened back up.

Can you send me some debugging output to help me visualize what you're seeing? You can do that using the following command:

```
repoman debug
```

Then try and disable the source code using the check and then close the window. Finally, paste the output from the terminal command here and I will be able to see what's going wrong.
