### ISSUE TITLE
[20.10] "Add Source" dialog hangs when attempting to add invalid source

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/repoman#75]
In 20.04, if I try to add an invalid source (using `http://test` as an example), I get a "Couldn't add source" dialog and the source is then added anyway (it's not good that the action is contrary to the error message, but that's sort of covered under this other issue: https://github.com/pop-os/repoman/issues/68).

In 20.10, if I try to add the same invalid source, instead of displaying an error message, the "Add Source" dialog box just hangs on its spinner indefinitely. Both the "Add" and "Cancel" buttons are greyed out, so I'm not able to back out or cancel without killing the program.

![repoman-issue-screenshot1](https://user-images.githubusercontent.com/7199422/96017943-d5d50700-0e07-11eb-84f1-5eeae9497ce0.png)

While I don't expect users to intentionally add bad source lines, this could happen in the event of a bad/incomplete copy/paste, and I would expect it to time out eventually so I can try again.

**Comment by isantop** [comment]
Hmmm, this is actually a different issue. `http://test` is theoretically a valid repository that can be added using repolib (it expands it to `deb http://test ${RELEASE} main`. The actual issue is that repoman is doing extra validation, which it shouldn't be.
