### ISSUE TITLE
Repoman's stuck if there's an error enabling a specific source [20.10 Upgrade]

### ISSUE THREAD

**Issue by mike-to-spec** [pop-os/repoman#82]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 ```
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Repoman: 
```
repoman:
  Installed: 2.0.0~1603294431~20.10~1555cb3
  Candidate: 2.0.0~1603294431~20.10~1555cb3
  Version table:
 *** 2.0.0~1603294431~20.10~1555cb3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```
**Issue/Bug Description:**

After updating to 20.10, editing to enable a specific source in Pop Shop's extra source doesn't work at all. 

In console: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 166, in on_edit_button_clicked
    self.do_edit(repo_name)
  File "/usr/lib/python3/dist-packages/repoman/list.py", line 188, in do_edit
    dialog.source.save_to_disk()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 144, in save_to_disk
    source_output = self.make_deblines()
  File "/usr/lib/python3/dist-packages/repolib/legacy_deb.py", line 175, in make_deblines
    toprint += f'{out_binary.make_debline()}\n'
  File "/usr/lib/python3/dist-packages/repolib/source.py", line 211, in make_debline
    line += self._get_options()
  File "/usr/lib/python3/dist-packages/repolib/source.py", line 427, in _get_options
    opt_str += f'{self.outoptions_d[key]}={self.options[key].replace(" ", ",")} '
KeyError: 'signed-by'


```

**Steps to reproduce (if you know):**

The source was added as such on 20.04: 

>  echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password.gpg] https://downloads.1password.com/linux/debian edge main' | sudo tee /etc/apt/sources.list.d/1password.list

After upgrade, open Pop Shop, go to Settings > Extra Source, find the 1Password source and edit to enable it. After that, you cannot leave the view, it can't be saved nor cancelled. 

![image](https://user-images.githubusercontent.com/370953/97087610-302c4f80-15e0-11eb-9743-df7094d355e4.png)

**Expected behavior:**

I expected to see the error on the view and be able to cancel it completely. 

**Other Notes:**

I can close the window by pressing `esc`.

**Comment by leviport** [comment]
@gumballdead I believe that is a different problem. There is an issue tracking that bug here: https://github.com/pop-os/repolib/issues/25

**Comment by bartlebee13** [comment]
@leviport my problem is the same issue as this: https://github.com/pop-os/repoman/issues/80

**Comment by bartlebee13** [comment]
Afaik its not the same issue as the index out of range error.

**Comment by isantop** [comment]
This should be fixed by the improved validation in pop-os/repolib#24 which has been released from staging.
